name: Shell Lint

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  shellcheck:
    uses: nikolareljin/ci-helpers/.github/workflows/ci.yml@production
    with:
      lint_command: |
        sudo apt clean
        sudo apt autoclean
        sudo apt-get update
        sudo apt-get install -y shellcheck
        STRICT=1 bash ./scripts/lint.sh
